version: "3.9"
services:
  app:
    image: php:8.3-apache
    ports:
      - "8081:80"
    working_dir: /var/www
    environment:
      THREAT_SRC: /app/src
    volumes:
      - ../:/var/www
      - ../psr15/public:/var/www/html
      - ../../:/app
    command: apache2-foreground
